### ISSUE TITLE
感谢大佬，做的很好，既美观又好用，提两个小问题

### ISSUE THREAD

**Issue by coderZoe** [toutoumu/QBittorrent-doc#2]
1. 点开种子详情，用户界面下，对于ipv6的显示会有些小问题，由于ipv6过长会溢出屏幕 
![5e6cb8d5ba876b3d65f025370fbe078](https://github.com/toutoumu/QBittorrent-doc/assets/55009317/68443499-f2f9-496e-a523-6dc96f90d974)
2. 希望能新增用户界面下的一些排序，如根据上传/下载速度排序用户

**Comment by toutoumu** [comment]
应该都改好了
