### ISSUE TITLE
transmission中多个种子变成一个了

### ISSUE THREAD

**Issue by wesmile8** [toutoumu/QBittorrent-doc#4]
如图所示transmission虽然能登录进去，但是里面的种子信息全部都变成了一个，希望大佬继续完善transmission
![64f0637e7b3eab6dc37e059cee7e9dd](https://github.com/toutoumu/QBittorrent-doc/assets/75376418/ed11db5c-2723-4169-9485-cca55987516e)

**Comment by toutoumu** [comment]
已经修复了，下载看看
