### ISSUE TITLE
Transmission部分还是显示不完全

### ISSUE THREAD

**Issue by wesmile8** [toutoumu/QBittorrent-doc#5]
**这是在transdroid中的显示：**
![S40204-10354061_org transdroid full](https://github.com/toutoumu/QBittorrent-doc/assets/75376418/c0ddbd30-33c4-4094-8890-10df266943a0)

**这是在QBittorrent-doc中的显示：**
![S40204-10314792_com toutoumu qbittorrent](https://github.com/toutoumu/QBittorrent-doc/assets/75376418/80df48ba-8b6f-423f-bcfb-434d5892474f)

**Comment by wesmile8** [comment]
我是通过群辉docker部署的transmission，下面是我的代码：
`docker run -d  --name=transmission -e PUID=1026 -e PGID=100 -e TZ=Asia/Shanghai -e TRANSMISSION_WEB_HOME=/transmission-web-control/src -e USER=*** -e PASS=***-p *** -p *** -p ***/udp -v /volume1/docker/transmission/data:/config -v /volume2/video/downloads:/downloads -v /volume1/docker/transmission/watchfolder:/watch -v /volume1/docker/transmission/webui:/transmission-web-control --restart unless-stopped linuxserver/transmission:latest`
我显示不全的原因和我部署方式和docker部署命令有关吗

**Comment by toutoumu** [comment]
您说的是标题显示不全对吧！这里我做了省略处理默认只显示两行，等有空了我找找有没有办法用，可自动调整字体大小的方式显示全部

**Comment by wesmile8** [comment]
> 您说的是标题显示不全对吧！这里我做了省略处理默认只显示两行，等有空了我找找有没有办法用，可自动调整字体大小的方式显示全部

好的，谢谢

**Comment by toutoumu** [comment]
1.0.3已修复该问题
